- hosts: localhost
  connection: local
  vars:
     ansible_remote_tmp: /tmp
     config:
       flatpak: "{{ lookup('template', 'configs/flatpak.yaml') | from_yaml }}"
       toolbox: "{{ lookup('template', 'configs/toolbox.yaml') | from_yaml }}"
       host: "{{ lookup('template', 'configs/host.yaml') | from_yaml }}"

  tasks:
     - name: Ensure directory {{ lookup('env','HOME') }}/.local/bin exists
       ansible.builtin.file:
         path: "{{ lookup('env','HOME') }}/.local/bin"
         state: directory
         mode: '0755'
       tags: [always]

     - name: Add flatpak remotes
       community.general.flatpak_remote:
         name: "{{ item.name }}"
         state: "{{ item.state }}"
         method: "{{ item.method }}"
         flatpakrepo_url: "{{ item.flatpakrepo_url }}"
       loop: "{{ config.flatpak.remotes }}"
       tags: [flatpak]

     - name: Setup flatpaks
       include_tasks: playbooks/setup/setup_flatpak.yaml
       tags: [always]
       args:
         apply:
           tags: [flatpak]
       loop: "{{ config.flatpak.flatpaks }}"
       loop_control:
         loop_var: flatpak

     - name: Create and configure toolbox
       include_tasks: playbooks/setup/setup_toolbox.yaml
       tags: [always]
       args:
         apply:
           tags: [toolbox, "{{ toolbox.name }}"]
       loop: "{{ config.toolbox }}"
       loop_control:
         loop_var: toolbox

     - name: Configure host
       include_tasks: playbooks/setup/setup_host.yaml
       tags: [always]
       args:
         apply:
           tags: [host]
       loop: "{{ config.host }}"
       loop_control:
         loop_var: host
