- name: Install and manage copr repositories {{ task_identifier }}
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: "{{ copr.state }}"
    name: "{{ copr.name }}"
  loop:
    - { name: 'otaylor/flatpak-module-tools-experimental', state: enabled }
  loop_control:
    loop_var: copr

- name: Install software {{ task_identifier }}
  ansible.builtin.dnf:
    state: present
    name:
      - '@Development tools'
      - '@RPM Development Tools'
      - flatpak-module-tools
      - nosync

- name: Make users passwordless for sudo in group wheel {{ task_identifier }}
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Install multi python packages with version specifiers
  ansible.builtin.pip:
    name:
      - rpmfluff
