groupinstall:
  - '@Chinese Support'
  - '@Development tools'
  - '@Fonts'
development:
  - SDL2-devel
  - android-tools
  - axel
  - bison
  - cabal-install
  - cmake
  - dejavu-sans-mono-fonts
  - dejavu-sans-mono-fonts
  - diffpdf
  - diffutils
  - dnf-plugins-core
  - distribution-gpg-keys
  - elfutils-libelf-devel
  - elfutils-libelf-devel-static
  - fedora-packager
  - fedpkg
  - ffmpeg
  - ffmpeg-devel
  - file
  - findutils
  - flex
  - ghc
  - git-tools
  - glx-utils
  - glxinfo
  - gparted
  - grubby
  - harfbuzz-icu
  - kernel-devel
  - kernel-modules
  - libavformat
  - libavformat-devel
  - libelf
  - libusb
  - libusb-devel
  - mesa-dri-drivers
  - mesa-vulkan-drivers
  - meson
  - ncurses-devel
  - ncurses-devel
  - openssl-devel
  - pesign
  - pipewire-libs
  - pipewire-pulseaudio
  - procps-ng
  - pulseaudio-libs
  - qt5-qtwayland
  - rpmdevtools
  - xdg-dbus-proxy
utils:
  - htop
  - nautilus
  - ncdu
  - zsh
  - wl-clipboard
  - xz
  - zip
  - unzip
  - which
  - xdg-utils
  - tmux
  - strace
  - scrcpy
  - skopeo
  - terminator
  - podenv
  - gnome-tweaks
misc:
  - xdg-desktop-portal-gtk
  - powerline
  - tmux-powerline
  - google-noto-emoji-color-fonts
  - google-noto-emoji-fonts
  - google-roboto-fonts
  - gtk4
