remotes:
  - name: fedora
    state: present
    flatpakrepo_url: oci+https://registry.fedoraproject.org
    method: system

  - name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

  - name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
    method: user

flatpaks:
  - name: org.gnome.TextEditor
    state: present
    method: user
    remote: flathub-beta
    cmds: [gtedit, gnome-text-editor]

  - name: org.gimp.GIMP
    state: present
    method: system
    remote: fedora
    cmds: [gimp]

  - name: org.gnome.gedit
    state: present
    method: user
    remote: flathub
    cmds: [gedit]

  - name: io.neovim.nvim
    state: present
    method: system
    remote: flathub
    cmds: [vi, vim, nvim]
    overrides:
      - { name: "--filesystem=/tmp", scope: user }

  - name: com.github.tchx84.Flatseal
    state: present
    method: system
    remote: flathub

  - name: com.brave.Browser
    state: present
    method: system
    remote: flathub-beta
    cmds: [brave]
