- key: /org/gnome/shell/favorite-apps
  value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'com.brave.Browser.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.TextEditor.desktop']"
- key: /org/gnome/desktop/calendar/show-weekdate
  value: "true" 
- key: /org/gnome/desktop/wm/preferences/button-layout
  value: "appmenu:minimize,maximize,close"
  single_quoted: yes 
- key: /org/gnome/desktop/wm/preferences/focus-mode
  value: click
  single_quoted: yes
- key: /org/gnome/desktop/sound/event-sounds
  value: "false"
- key: /org/gnome/desktop/sound/allow-volume-above-100-percent
  value: "true" 
- key: /org/gnome/desktop/interface/clock-format
  value: 24 
- key: /org/gnome/desktop/interface/show-battery-percentage
  value: "true" 
- key: /org/gnome/desktop/interface/clock-show-weekday
  value: "true" 
- key: /org/gnome/desktop/interface/clock-show-seconds
  value: "true"
- key: /org/gnome/desktop/interface/gtk-theme
  value: Adwaita-dark
  single_quoted: yes 
- key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
  value: "false" 
- key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
  value: "true" 
- key: /org/gnome/desktop/peripherals/touchpad/disable-while-typing
  value: "true" 
- key: /org/gnome/shell/extensions/caffeine/inhibit-apps
  value: "['com.brave.Browser.desktop']"
- key: /org/gnome/shell/extensions/dash-to-panel/panel-positions
  value: '{"0":"TOP","1":"TOP","2":"TOP","3":"TOP"}'
  single_quoted: yes 
- key: /org/gnome/shell/extensions/dash-to-panel/available-monitors
  value: "[0, 1]" 
- key: /org/gnome/shell/extensions/dash-to-panel/primary-monitor
  value: 0 
- key: /org/gnome/shell/extensions/dash-to-panel/multi-monitors
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/panel-element-positions-monitors-sync
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/trans-use-custom-opacity
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/isolate-workspaces
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/isolate-monitors
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/overview-click-to-exit
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/stockgs-keep-dash
  value: "true" 
- key: /org/gnome/shell/extensions/clipboard-indicator/history-size
  value: 60 
- key: /org/gnome/shell/extensions/clipboard-indicator/move-item-first
  value: "true" 
- key: /org/gnome/shell/extensions/dash-to-panel/panel-element-positions
  value: '{{ lookup("file", "templates/dash-to-panel_panel-element-positions.json") }}'
  single_quoted: yes 

