- name: thinkXPS
  tasks: 
    - playbooks/host/tasks_host_default.yaml
    - playbooks/host/tasks_host_rpm_ostree.yaml
    - playbooks/host/tasks_host_systemd.yaml
    - playbooks/host/tasks_host_python.yaml
    - playbooks/host/tasks_host_gnome_extensions.yaml
    - playbooks/host/tasks_host_dconf.yaml
  gnome:
    extensions:
      # Do not define "gnome_version" if extension is pre-installed or installed via rpm-ostree
      # extensions without "gnome_version" will only action "disable" and "enable" extension tasks.
      # Set "gnome_version" to "current" if you want to use your currently installed version.
      # Setting "gnome_Version" to "current" might break if extension is not published for your version.
      - { uuid: 'background-logo@fedorahosted.org', enabled: no }
      - { uuid: 'user-theme@gnome-shell-extensions.gcampax.github.com', gnome_version: current, enabled: yes }
      - { uuid: 'caffeine@patapon.info', gnome_version: current, enabled: yes }
      - { uuid: 'clipboard-indicator@tudmotu.com', gnome_version: current, enabled: yes }
      - { uuid: 'trayIconsReloaded@selfmade.pl', gnome_version: current, enabled: yes }
      - { uuid: 'dash-to-panel@jderose9.github.com', gnome_version: '41', enabled: yes }
    dconf:
      - { key: '/org/gnome/desktop/calendar/show-weekdate', value: 'true' }
      - { key: '/org/gnome/desktop/wm/preferences/button-layout', value: '''appmenu:minimize,maximize,close''' }
      - { key: '/org/gnome/desktop/wm/preferences/focus-mode', value: '''sloppy''' }
      - { key: '/org/gnome/desktop/sound/event-sounds', value: 'false' }
      - { key: '/org/gnome/desktop/sound/allow-volume-above-100-percent', value: 'true' }
      - { key: '/org/gnome/desktop/interface/clock-format', value: '24' }
      - { key: '/org/gnome/desktop/interface/show-battery-percentage', value: 'true' }
      - { key: '/org/gnome/desktop/interface/clock-show-weekday', value: 'true' }
      - { key: '/org/gnome/desktop/interface/clock-show-seconds', value: 'true' }
      - { key: '/org/gnome/desktop/interface/gtk-theme', value: '''Adwaita-dark''' }
      - { key: '/org/gnome/desktop/peripherals/touchpad/natural-scroll', value: 'false' }
      - { key: '/org/gnome/desktop/peripherals/touchpad/tap-to-click', value: 'true' }
      - { key: '/org/gnome/desktop/peripherals/touchpad/disable-while-typing', value: 'true' }
      - { key: '/org/gnome/shell/extensions/caffeine/inhibit-apps', value: '[''com.brave.Browser.desktop'']' }
